#include "f4se/Hooks_Scaleform.cpp"
#include "f4se_common/SafeWrite.h"
#include "f4se_common/BranchTrampoline.h"
#include "f4se/GameSettings.h"
#include "xbyak/xbyak.h"
#include <shlobj.h>
#include <stdio.h>
#include <string>
#include <Windows.h>
#include <sstream> 
#include <time.h>
#include "common/IDebugLog.h"
#include <chrono>
#include <algorithm>
#include <ratio>
#include <ctime>
#include <psapi.h>
#include <mutex>
#include <TlHelp32.h>
#include "PerfCounter.h"
#include "D3D11hook.h"
#include <d3d11.h>
#include <dxgi.h>
#include <dxgi1_6.h>
#include <vector>
#include <functional>
#include "JITASM.h"
#include <wrl/client.h>
#include "config.h"
#include "HighFPSPhysicsFix.h"